trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 1   # change to 0 if you need full git history

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'